---
- name: Install Python3 Pip
  apt: name=python3-pip

- name: Install npm
  apt: name=npm

- name: Install git for custom installs further down the line
  apt: name=git

- name: Install Cargo for Rust packages
  apt: name=cargo
