---
- name: Install curl
  apt: name=curl

- name: Install nmap
  apt: name=nmap

- name: Install WhoIs
  apt: name=whois

- name: Add NordVPN client repository and key
  apt:
    deb: https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb

- name: Install NordVPN client
  apt: 
    name: nordvpn
    update_cache: yes

- name: Install httpie
  apt: name=httpie
