---
- name: Provision main machine
  hosts: "{{ variable_host | default('localhost') }}"
  remote_user: "{{ lookup('env','USER') }}"
  become: yes


  roles:
    - { role: package-managers, tags: package }
    - { role: keyboard-basics, tags: keyboard }
    - { role: uhk, tags: [keyboard, uhk] }
    - { role: copypaste, tags: copypaste }
    - { role: terminal, tags: terminal }
    - { role: gantsign.oh-my-zsh, tags: terminal, users: [{ username: david }]}
    - { role: auth, tags: auth }
    - { role: net, tags: net }
    - { role: browser, tags: browse }
    - { role: messaging, tags: msg }
