---
- name: Provision main machine
  hosts: localhost
  remote_user: "{{ lookup('env','USER') }}"
  become: yes

  roles:
    - { role: package-managers, tags: package }
    - { role: keyboard-basics, tags: keyboard }
    - { role: copypaste, tags: copypaste }
    - { role: terminal, tags: terminal }
    - { role: auth, tags: auth }
    - { role: net, tags: net }
    - { role: browser, tags: browse }
    - { role: messaging, tags: msg }
