---
- name: Install zsh
  apt: name=zsh

- name: Create symlink for XDG oh-my-zsh dir to non-XDG
  become: no
  file:
   src: "~/.oh-my-zsh"
   dest: "~/.config/oh-my-zsh"
   state: link

- name: Install zsh plugin autosuggestions
  apt: name=zsh-autosuggestions

- name: Install zsh-autosuggestions oh-my-zsh binding
  become: no
  git:
    repo: git@github.com:zsh-users/zsh-autosuggestions
    dest: ~/.config/oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install tmux
  apt: name=tmux

- name: Ensure tmux plugin dir
  become: no
  file:
    path: ~/.config/tmux/plugins
    state: directory

- name: Install tmux plugin manager
  become: no
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.config/tmux/plugins/tpm
    force: yes

- name: Run tmux plugin manager install script
  become: no
  command: ~/.config/tmux/plugins/tpm/bin/install_plugins
  environment:
    TMUX_PLUGIN_MANAGER_PATH: "$HOME/.config/tmux/plugins"

- name: Install xclip, for copy-pasting
  apt: name=xclip

- name: Install AutoJump, for easy dir access
  apt: name=autojump

- name: Install SilverSearcher, for easy file finding
  apt: name=silversearcher-ag

- name: Install bat, a cat alternative
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.15.4/bat-musl_0.15.4_amd64.deb

- name: Install Exa, an ls alternative
  unarchive:
    src: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    dest: /tmp/
    remote_src: yes

- name: Move Exa binary to bin folder
  command: mv /tmp/exa-linux-x86_64 /usr/local/bin/exa

- name: Install htop, an alternative to top
  apt: name=htop

- name: Enable cursor blinking
  command: gsettings set org.gnome.desktop.interface cursor-blink true

- name: Set cursor blink speed to less geriatric (namely fast)
  command: gsettings set org.gnome.desktop.interface cursor-blink-time 400

- name: Practically disable cursor blink timeout, because who would ever want that...
  command: gsettings set org.gnome.desktop.interface cursor-blink-timeout 999999

- name: Install neofetch for easy OS and system info
  apt: name=neofetch

- name: Install jq for JSON processing
  apt: name=jq

- name: Install httpie
  apt: name=httpie

- name: Install broot
  become: no
  command: cargo install broot

- name: Install broot deps
  become: no
  command: broot --install
